raft:
  connectionTimeoutMillis: 1000
  electionTimeoutMillis: 500
  heartbeatIntervalMillis: 50
  consensusTimeoutMillis: 100
  nodes:
  - id: node-0
    ipAddress: localhost
    port: 15000
  - id: node-1
    ipAddress: localhost
    port: 15001
  - id: node-2
    ipAddress: localhost
    port: 15002
  - id: node-3
    ipAddress: localhost
    port: 15003
  - id: node-4
    ipAddress: localhost
    port: 15004
  size: 5
# randomly select the port
server:
  port: 0
logging:
  level:
    org.consensus: INFO
