/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.39). https://github.com/swagger-api/swagger-codegen Do not edit the class manually.
 */
package org.consensus.example;

import javax.validation.Valid;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

@Validated
@RequestMapping(value = "/v1")
public interface KeyValueApi {

    @RequestMapping(value = "/kvstore", produces = {"application/json"}, consumes = {"application/json"}, method = RequestMethod.DELETE)
    ResponseEntity<String> delete(@Valid @RequestBody KeyValueModel model);

    @RequestMapping(value = "/kvstore", produces = {"application/json"}, consumes = {"application/json"}, method = RequestMethod.GET)
    ResponseEntity<String> get(@Valid @RequestBody KeyValueModel model);

    @RequestMapping(value = "/kvstore", produces = {"application/json"}, consumes = {"application/json"}, method = RequestMethod.PUT)
    ResponseEntity<String> put(@Valid @RequestBody KeyValueModel model);

}
